development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: apis_iphone
  username: root
  password: planeta2014

testing:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: apis_iphone
  username: root
  password: planeta2014

production:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: apis_iphone
  username: root
  password: planeta2014
